### PR TITLE
Merge existing package.json to package created by embroider build

### PR DESCRIPTION
**Pull request by dnalagatla**
https://github.com/embroider-build/embroider/issues/160

### CODE REVIEW

**Comment by ef4** [comment]
Thanks, very nice work.

**Comment by ef4** [comment]
@dnalagatla this had to get reverted, see #342.

**Comment by st-h** [comment]
@ef4 is there any other means to fix this or a work around? I am seeing the error described in #160, which was supposed to be fixed by this PR

**Comment by ef4** [comment]
@st-h I reopened #160 to cover this.

We can still merge the package.json, but it needs to be implemented differently. This implementation was merging from the wrong spot in the build process.

**Comment by st-h** [comment]
@ef4 thanks for the clarification. I am just trying to give embroider a spin every now and then to see if I can make it work with my app. But I can hold off, if it's still too early. Unfortunately that I can't dedicate more time to fix stuff right now.

**Comment by dnalagatla** [comment]
> @st-h I reopened #160 to cover this.
> 
> We can still merge the package.json, but it needs to be implemented differently. This implementation was merging from the wrong spot in the build process.

hi, @ef4  I am going to look into this issue. Can you please provide details regarding where the merging of package.json should happen. I can take a look into that.

**Comment by ef4** [comment]
See https://github.com/embroider-build/embroider/pull/383#issuecomment-584386920

**Pull request merged**
