### PR TITLE
Add app.import + prepend test (to confirm they work)

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
hmm, seems to work. Perfect.

**Comment by ef4** [comment]
This is ok but if you add any more app.import tests, please put them here:

https://github.com/embroider-build/embroider/blob/master/packages/compat/tests/app-import-test.ts

**Comment by stefanpenner** [comment]
Sure

**Comment by stefanpenner** [comment]
I can migrate this one over as well.

**Pull request merged**
