### PR TITLE
Enable parallelization of @embroider/macros in non-Embroider builds

### LINKED ISSUE #671: `@embroider/macros` is not parallelizable
Quick example PR over in ember-engines: https://github.com/ember-engines/ember-engines/pull/751

Haven't had much time to dig into this just yet, but it seems like the plugins registered here:

https://github.com/embroider-build/embroider/blob/d21b77e1d0e291aa96602eec54519910fc5d13bd/packages/macros/src/ember-addon-main.ts#L88-L94

Need to be including the `parallelBabel` property (which is used by [ember-cli-htmlbars here](https://github.com/ember-cli/ember-cli-htmlbars/blob/1633af978e1eb293bba1c03c65bff3f41d9e707f/lib/utils.js#L248-L253)).

Here is an example from ember-cli-htmlbars own test suite:

```js
    registry.add('htmlbars-ast-plugin', {
      name: 'module-name-inliner',
      baseDir() {
        return __dirname;
      },
      parallelBabel: {
        requireFile: __filename,
        buildUsing: 'buildPlugin',
        params: {},
      },
      plugin(env) {
        let { builders } = env.syntax;

        return {
          name: 'module-name-inliner',

          visitor: {
            PathExpression(node) {
              if (node.original === 'module-name-inliner') {
                // replacing the path with a string literal, like this
                // {{"the-module-name-here"}}
                return builders.string(env.moduleName);
              }
            },
          },
        };
      },
    });
```

### PR DESCRIPTION
**Pull request by thoov**
Closes #671

### CODE REVIEW

**Comment by rwjblue** [comment]
Ready for a rebase

**Comment by thoov** [comment]
> Ready for a rebase

Done

**Review by rwjblue — APPROVED** [review]

**Comment by chriskrycho** [comment]
Not urgent, but checking in for the sake of unblocking usage of `ember-element-helper@5`: ETA on getting this into a 0.42.3 release?

**Comment by chriskrycho** [comment]
…literally 5 seconds after I posted this, 0.42.3 was released with the fix. @rwjblue!!!

**Pull request merged**
