### PR TITLE
Add `{{macroMaybeModifier}}` template macro

### LINKED ISSUE #680: macroMaybeModifier needed?
I just came across a use case where I wanted to use `@embroider/macros` to conditionally apply a modifier. As we are in element space, we cannot simply use `{{#if}}` here. 

The same applied for setting attributes conditionally, but this is explicitly covered by `macroMaybeAttrs`. Do we eventually need an equivalent for this, `macroMaybeModifier`?

### PR DESCRIPTION
**Pull request by simonihmig**
Closes #680

### CODE REVIEW

**Comment by simonihmig** [comment]
Just realized I should add some e2e tests in `macro-tests`. Will do that later...

Also no documentation yet, as we didn't have any for template macros yet, and I felt adding all of that was out of scope for this PR.

Also tests are failing for canary, but also for other PRs, so seems unrelated.

**Comment by simonihmig** [comment]
> Just realized I should add some e2e tests in macro-tests. Will do that later...

Done!

**Review by ef4 — APPROVED** [review]
Thanks, this looks good.

**Comment by simonihmig** [comment]
I marked this PR as draft to not accidentally merge this prematurely, as we should probably first try out this alternative approach before introducing a new API here: https://github.com/embroider-build/embroider/issues/680#issuecomment-779481710

**Comment by rwjblue** [comment]
Replaced by #712

**Pull request closed without merging**
