### PR TITLE
Fingerprint scripts and styles in production

### LINKED ISSUE #289: Is there a way to fingerprint vendor.js?
Is there a way to fingerprint vendor.js and other assets like images and css?

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #289

Tested it locally in an app (`ember s --prod`). 
Do we have any test coverage here for the stage 3 part, especially the production variant? AFAICT we only have one test-package that runs its [tests in a production build](https://github.com/embroider-build/embroider/blob/master/test-packages/fastboot-app/package.json#L22) in CI.

### CODE REVIEW

**Comment by simonihmig** [comment]
There is one issue here, that I could observe locally. However I believe this was just uncovered by the renaming of files, but the root cause is elsewhere. Created this issue: #622

**Comment by simonihmig** [comment]
> AFAICT we only have one test-package that runs its tests in a production build in CI.

And it seems exactly this is failing here 🙈
Will need to investigate...

**Comment by simonihmig** [comment]
> And it seems exactly this is failing here

Seems we have to explicitly exclude `testem.js` from fingerprinting, otherwise testing in a  production environment does not work. Note that `ember s --prod` works (when opening `/tests` in the browser), it seems just the testem integration is broken when fingerprinting everything.

A quick Google search revealed a similar fix for ember-cli in this old PR: https://github.com/ember-cli/ember-cli/pull/1230/files#diff-8098951b282ee3680dd2afa8d34b95c7e542d90d65961bb60cbf897779c54eadR411

**Review by lifeart — APPROVED** [review]

**Comment by ef4** [comment]
Thanks. I used the existing `data-embroider-ignore` feature to avoid needing to special-case testem. I think it's reasonable to require people to annotate scripts that they don't want to go through the build.

**Pull request merged**
