### PR TITLE
bump ember-source to 3.27

### PR DESCRIPTION
**Pull request by stefanpenner**
incremental ember-source bump

### CODE REVIEW

**Comment by rwjblue** [comment]
Should probably go to 3.28 (it is current release, and future LTS candidate)

**Comment by stefanpenner** [comment]
@rwjblue the current version isn't green, unless there is an upstream fix I would like to make this work before compounding the problems

**Comment by rwjblue** [comment]
> the current version isn't green

Do you mean there are changes in ember-source@3.28.0 that introduces new failures (vs 3.27)? Also, this does seem to introduce failures (even with 3.27), unless I'm mis-reading the actions that are failing.

> unless there is an upstream fix I would like to make this work before compounding the problems

Sure, seems fine. I didn't realize that you had identified specific ember-source@3.28 issues.

**Comment by stefanpenner** [comment]
@rwjblue 3.26 -> 3.27 introduces the above failures. My plan is to resolve them, prior to attempting 3.28.

**Comment by rwjblue** [comment]
AH!!! Gotcha, I didn't realize this was WIP, sorry 😞

**Comment by stefanpenner** [comment]
I believe the current failures are actually related to https://github.com/embroider-build/embroider/pull/866/

**Comment by stefanpenner** [comment]
basically a duplicate of https://github.com/embroider-build/embroider/pull/866

**Pull request closed without merging**
