### PR TITLE
Move the app files in an embroider rewritten app into virtualised content

### LINKED ISSUE #1708: move the app files in an embroider rewritten app into virtualised content
Right now there are some things that require the rewritten-app to have extra imports added to it. For example, if you look at `node_modules/.emberoider/rewritten-app/assets/app-name.js` you will see a long list of `define()` calls with importSync() to parts of your app.

This needs to work more like the `-emborider-implicit-modules` and it should have a pojo that is imported and then defined in a loop 👍

### PR DESCRIPTION
**Pull request by lolmaus**
fixes #1708

### CODE REVIEW

**Comment by lolmaus** [comment]
So far, the app builds fine, but the runtime crashes with:

```
Uncaught Error: app-template/initializers/load-bootstrap-config must have a default export
    at resolveInitializer (index.js:15:11)
    at registerInitializers (index.js:24:21)
    at loadInitializers (index.js:59:3)
    at eval (app.js:35:68)
    at ./app.js (chunk.a5e189bfbf844671e4cf.js:18:1)
    at __webpack_require__ (chunk.3ece5f9b18ac30b27fc9.js:31:41)
    at eval (app-template.js:9:116)
    at ./assets/app-template.js (chunk.a5e189bfbf844671e4cf.js:28:1)
    at __webpack_require__ (chunk.3ece5f9b18ac30b27fc9.js:31:41)
    at chunk.3ece5f9b18ac30b27fc9.js:171:216
```

**Comment by lolmaus** [comment]
Here's how the virtual `-embroider-app-modules.js` file looks like:

```js
import { getGlobalConfig, macroCondition } from '@embroider/macros';
import * as appMod0 from "@ef4/namespaced-app/app.js";
import * as appMod1 from "@ef4/namespaced-app/config/environment.js";
import * as appMod2 from "@ef4/namespaced-app/router.js";
import * as appMod3 from "@ef4/namespaced-app/component-managers/glimmer.js";
import * as appMod4 from "@ef4/namespaced-app/initializers/app-version.js";
import * as appMod5 from "@ef4/namespaced-app/data-adapter.js";
import * as appMod6 from "@ef4/namespaced-app/initializers/ember-data.js";
import * as appMod7 from "@ef4/namespaced-app/services/store.js";
import * as appMod8 from "@ef4/namespaced-app/transforms/boolean.js";
import * as appMod9 from "@ef4/namespaced-app/transforms/date.js";
import * as appMod10 from "@ef4/namespaced-app/transforms/number.js";
import * as appMod11 from "@ef4/namespaced-app/transforms/string.js";
import * as appMod12 from "@ef4/namespaced-app/services/page-title-list.js";
import * as appMod13 from "@ef4/namespaced-app/services/page-title.js";
import * as appMod14 from "@ef4/namespaced-app/initializers/container-debug-adapter.js";
import * as appMod15 from "@ef4/namespaced-app/components/import-lodash.js";
import * as appMod16 from "@ef4/namespaced-app/helpers/app-version.js";
import * as appMod17 from "@ef4/namespaced-app/helpers/pluralize.js";
import * as appMod18 from "@ef4/namespaced-app/helpers/singularize.js";
import * as appMod19 from "@ef4/namespaced-app/helpers/page-title.js";
import * as appMod20 from "@ef4/namespaced-app/templates/application.hbs";
import * as fastbootOnlyAppMod0 from "@ef4/namespaced-app/instance-initializers/setup-fetch.js";
const modules = {
  "@ef4/namespaced-app/app": appMod0,
  "@ef4/namespaced-app/config/environment": appMod1,
  "@ef4/namespaced-app/router": appMod2,
  "@ef4/namespaced-app/component-managers/glimmer": appMod3,
  "@ef4/namespaced-app/initializers/app-version": appMod4,
  "@ef4/namespaced-app/data-adapter": appMod5,
  "@ef4/namespaced-app/initializers/ember-data": appMod6,
  "@ef4/namespaced-app/services/store": appMod7,
  "@ef4/namespaced-app/transforms/boolean": appMod8,
  "@ef4/namespaced-app/transforms/date": appMod9,
  "@ef4/namespaced-app/transforms/number": appMod10,
  "@ef4/namespaced-app/transforms/string": appMod11,
  "@ef4/namespaced-app/services/page-title-list": appMod12,
  "@ef4/namespaced-app/services/page-title": appMod13,
  "@ef4/namespaced-app/initializers/container-debug-adapter": appMod14,
  "@ef4/namespaced-app/components/import-lodash": appMod15,
  "@ef4/namespaced-app/helpers/app-version": appMod16,
  "@ef4/namespaced-app/helpers/pluralize": appMod17,
  "@ef4/namespaced-app/helpers/singularize": appMod18,
  "@ef4/namespaced-app/helpers/page-title": appMod19,
  "@ef4/namespaced-app/templates/application": appMod20
};
if (macroCondition(getGlobalConfig().fastboot?.isRunning)) {
  modules["@ef4/namespaced-app/instance-initializers/setup-fetch"] = fastbootOnlyAppMod0;
}
export default modules;
```

**Comment by lolmaus** [comment]
Previously, there was a physical file `my-app/node_modules/.embroider/rewritten-app/assets/app-template.js` that contained this:

```js
d("app-template/adapters/post", function(){ return i("app-template/adapters/post.js");});
d("app-template/app", function(){ return i("app-template/app.js");});
d("app-template/config/environment", function(){ return i("app-template/config/environment.js");});
d("app-template/models/post", function(){ return i("app-template/models/post.js");});
d("app-template/router", function(){ return i("app-template/router.js");});
d("app-template/serializers/application", function(){ return i("app-template/serializers/application.js");});
d("app-template/component-managers/glimmer", function(){ return i("app-template/component-managers/glimmer.js");});
d("app-template/services/-ensure-registered", function(){ return i("app-template/services/-ensure-registered.js");});
d("app-template/initializers/load-bootstrap-config", function(){ return i("app-template/initializers/load-bootstrap-config.js");});
d("app-template/initializers/app-version", function(){ return i("app-template/initializers/app-version.js");});
d("app-template/data-adapter", function(){ return i("app-template/data-adapter.js");});
d("app-template/initializers/ember-data", function(){ return i("app-template/initializers/ember-data.js");});
d("app-template/services/store", function(){ return i("app-template/services/store.js");});
d("app-template/transforms/boolean", function(){ return i("app-template/transforms/boolean.js");});
d("app-template/transforms/date", function(){ return i("app-template/transforms/date.js");});
d("app-template/transforms/number", function(){ return i("app-template/transforms/number.js");});
d("app-template/transforms/number", function(){ return i("app-template/transforms/number.js");});
d("app-template/transforms/string", function(){ return i("app-template/transforms/string.js");});
d("app-template/services/page-title-list", function(){ return i("app-template/services/page-title-list.js");});
d("app-template/services/page-title", function(){ return i("app-template/services/page-title.js");});
d("app-template/initializers/container-debug-adapter", function(){ return i("app-template/initializers/container-debug-adapter.js");});
d("app-template/templates/ember-data-example", function(){ return i("app-template/templates/ember-data-example.hbs");});
d("app-template/routes/ember-data-example", function(){ return i("app-template/routes/ember-data-example.js");});
d("app-template/templates/application", function(){ return i("app-template/templates/application.hbs");});
d("app-template/templates/components-example", function(){ return i("app-template/templates/components-example.hbs");});
d("app-template/templates/helpers-example", function(){ return i("app-template/templates/helpers-example.hbs");});
d("app-template/templates/macros-example", function(){ return i("app-template/templates/macros-example.hbs");});
d("app-template/templates/static-component-rules-example", function(){ return i("app-template/templates/static-component-rules-example.hbs");});
```

**Comment by mansona** [comment]
we moved in a slightly different direction here, instead of extracting just the app files to be virtualised we moved the whole entry point: https://github.com/embroider-build/embroider/pull/1779

**Pull request closed without merging**
