### PR TITLE
[vite entry point] add gjs + gts extension for resolvable extensions

### PR DESCRIPTION
**Pull request by patricklx**
add gjs+gts as resolveable extensions for vite entry point asset file

### CODE REVIEW

**Comment by ef4** [comment]
Hi, I need more detail to understand what you're trying to do here.

`resolvableExtensions` is trying to match existing ember-cli behaviors and those don't actually resolve gjs/gts. I suspect there might be better place to put this fix to achieve what you're trying to achieve.

**Comment by patricklx** [comment]
It's possible to have gts/gjs files for templates with ember-route-templates. 
It's possible to transform them before starting vite, but  i would like vite to do the transform instead.
Also because I'm working to make it work to load everything from app dir instead of rewritten-app.
Which is mostly working now, except for this.

**Comment by ef4** [comment]
Sure but the [gjs plugin you've also been working on](https://github.com/embroider-build/embroider/pull/1680/files) already resolve gjs/gts. I still don't understand why it would be needed here in compat-app-builder too.

**Comment by patricklx** [comment]
i think this also makes sense without having vite load everything from root.
it can load gts/gjs files directly and we can also then remove `enableTypeScriptTransform` in ember-cli-build as vite can do it. making hot reload even faster

**Comment by ef4** [comment]
It's not OK to sometimes load from root and sometimes from the rewritten app, and so long as the files existing in the rewritten app they are resolvable. 

If you have both, vite will duplicate them.

We are quite close to eliminating rewritten app entirely.

**Comment by patricklx** [comment]
Right, what i meant in my last statement is that embroider could just copy the gts/gjs files to the rewritten-app and have vite resolve them. 
But the issue would remain that the route.gts would be missing from the entry point defines.
It would then lead to issues in the app, because ember would use the default router instead.

It's good to hear that rewritten-app is soon gone.

**Comment by patricklx** [comment]
Wip here: https://github.com/embroider-build/embroider/pull/1695

**Comment by patricklx** [comment]
reopen to separte out of big vite  pr

**Comment by patricklx** [comment]
moved to #1718

**Pull request closed without merging**
