### PR TITLE
Replace loader-utils with built-in webpack 5 functionality

### PR DESCRIPTION
**Pull request by mydea**
Webpack has built-in types now, which seem to conflict with `@types/loader-utils`. I think we can just remove this dependency - see https://github.com/webpack/loader-utils/issues/179.

Fixes https://github.com/embroider-build/embroider/issues/819

### CODE REVIEW

**Comment by mydea** [comment]
I rebased on latest master.

**Comment by rwjblue** [comment]
Kicked off CI

**Comment by chancancode** [comment]
We can't just remove the types. We currently use `getOptions` [here](https://github.com/embroider-build/embroider/blob/a2883a9764cbee1e538d03c10384bf76834cacaf/packages/hbs-loader/src/index.ts#L13). Removing the types package would cause the import itself to become a type error/any. Instead, I believe the recommendation was that we should remove the `loader-utils` package itself and switch from `getOptions` to using [the (supposedly, I haven't verified) equivalent provided by webpack 5](https://webpack.js.org/api/loaders/#thisgetoptionsschema).

@mydea would you work on that?

**Comment by chancancode** [comment]
I think you can also address [this](https://github.com/embroider-build/embroider/blob/a2883a9764cbee1e538d03c10384bf76834cacaf/packages/hbs-loader/src/index.ts#L9-L10) while you are there. It seems like recent versions of webpack does have a type for [`LoaderContext`](https://github.com/webpack/webpack/blob/7102df3bb52a33529ff5db4fdf34484d2a359a49/types.d.ts#L5852), further, it takes a generic slot for the options so it could just be `function hbsLoader(this: LoaderContext<HbsLoaderConfig>, ...)` and `this.getOptions()` should Just Work™.

**Comment by mydea** [comment]
I will give it a try!

**Comment by mydea** [comment]
Hmm, does hbs-loader need to remain compatible with webpack 4? Meaning, do I need to build this in a way that it _either_ uses the new webpack loader, _or_ `loader-utils`, or can I update that package to webpack 5 and just use that? 

I would go with the latter (`@embroider/webpack` relies on 5.x already anyhow), but if it should be the former I'm not sure what approach I should take to achieve that.

**Comment by mydea** [comment]
I made a PR updating webpack peerDependency to 5 for hbs-loader, and replacing loader-utils with the built-in functionality & the new types.

**Comment by ef4** [comment]
Thanks!

**Pull request merged**
