### PR TITLE
was missing amdCompatibility

### PR DESCRIPTION
**Pull request by patricklx**

### CODE REVIEW

**Comment by mansona** [comment]
We're in the process of removing all this 🤔 https://github.com/embroider-build/embroider/pull/2103

**Comment by patricklx** [comment]
I guess I could just use my own import alias in vite

**Comment by patricklx** [comment]
Well, it doesn't work by default, yes. But it can be made to work. Could also add a compat adapter maybe

**Comment by patricklx** [comment]
mmm, i saw @ef4 had an alternative implementation idea for ember-fetch with embroider macros. maybe it's time to look at that

**Comment by ef4** [comment]
ember-fetch could be simplified to keep working with its same public api without relying on AMD. All it needs is our renamed-modules feature in its ember-addon metadata.

**Comment by ef4** [comment]
But yes. We’re about to drop all AMD support. There will be no AMD loader. I guess people could re-add it if they want to, but nothing in our core is going to use it.

**Pull request closed without merging**
