### PR TITLE
Upgrade ember-qunit to address ember-canary compatibility issue curre…

### PR DESCRIPTION
**Pull request by stefanpenner**
…ntly breaking CI

### CODE REVIEW

**Comment by stefanpenner** [comment]
I'm in meetings the rest of the day. I'll look at that next.

**Comment by stefanpenner** [comment]
I'm going to resume this, this week

**Comment by stefanpenner** [comment]
This is currently blocked on releasing https://github.com/emberjs/ember-test-helpers/commit/cbbcf8d0b890f1ed0ff2ac3ae5c82760c574d56c

**Comment by ef4** [comment]
Superseded by #911

**Pull request closed without merging**
