### PR TITLE
Fix synthesized template-only components crash

### PR DESCRIPTION
**Pull request by chancancode**
This fixes ~~the first scenario detailed in~~ #1619. See the individual commit messages for details.

### CODE REVIEW

**Comment by chancancode** [comment]
Not sure if we currently have infrastructure for testing rebuilds?

**Comment by chancancode** [comment]
This only fixed half of the issues (which is fine, this can still be reviewed/merged/released as-is). I had incorrectly assumed that the second problem in #1619, while incorrect, does not result in crashes. I was wrong and I have added a third scenario (which may even be the dominate kind of crashes) in the issue.

**Comment by chancancode** [comment]
That would be great!

**Comment by mansona** [comment]
@chancancode we finally ironed out the issues with https://github.com/embroider-build/embroider/pull/1624 (I'm done with windows 😭) so you can create the watch mode tests now 👍 

Let me know if you have any questions about the setup 👍

**Comment by chancancode** [comment]
Oops I accidentally pushed everything to #1632 so I’ll just close this

**Pull request closed without merging**
