### PR TITLE
fix windows file paths issues

### PR DESCRIPTION
**Pull request by lifeart**
fix for https://github.com/embroider-build/embroider/issues/146
https://github.com/embroider-build/embroider/issues/74

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for working on this.

Is `.charAt(1) === ':'` safe? It seems like it would also match legal unix paths. 

Can we use [path.isAbsolute](https://nodejs.org/dist/latest-v10.x/docs/api/path.html#path_path_isabsolute_path) instead? I think that would replace the need for both kinds of checks: `path[0] === '/'` and `path.chatAt[1] === ':'`.

**Comment by lifeart** [comment]
> Thanks for working on this.
> 
> Is `.charAt(1) === ':'` safe? It seems like it would also match legal unix paths.
> 
> Can we use [path.isAbsolute](https://nodejs.org/dist/latest-v10.x/docs/api/path.html#path_path_isabsolute_path) instead? I think that would replace the need for both kinds of checks: `path[0] === '/'` and `path.chatAt[1] === ':'`.

I think it's really rare case for second symbol = `:` in unix. I don't like this slicing approach at all, it can be an better way, but, embroider not working in windows at all (after this pr I have ussies): 

image

incorrect `define` paths for some deps, full windows file path in `moduleName` property of compiled template.


@ef4 thank for feedback! I'm not against proposed updates, but, I think we can delay it until we get embroider happy path for windows.

**Comment by ef4** [comment]
A critical thing to sort out is that some paths are *filesystem* paths and therefore need OS-dependent handling, but other paths are *urls*, which should not get OS-dependent handling.

So it's probably not going to work if you just look for all the places that are using `/` explicitly and change them to `path.sep`. Some of those are URLs that are really supposed to always use `/`.

**Comment by ef4** [comment]
Also I guess not just URLs, but also "runtime paths" as seen by Ember and loader.js, which always use `/` as the separator regardless of operating system.

**Comment by lifeart** [comment]
Right, regarding fixes, 
`packages/compat/src/moved-package-cache.ts` - don't side `\\` in requrejs
`packages/core/src/app.ts` - don't side `\\` in requrejs
`packages/webpack/src/ember-webpack.ts` - don't side `\\` in requrejs

only posibble `siding` change in `packages/core/src/package-cache.ts`, but, it's critical change to get `embroider` working on windows.

looks like paths from `packages/core/src/package-cache.ts`, `ownerOfFile` - used in packaging and produce this side effects

**Comment by lifeart** [comment]
@ef4 using this branch I able to build & serve ember app (https://github.com/krausest/js-framework-benchmark/tree/master/frameworks/keyed/ember) and it's working.

Issues: 

webpack failing in case of resolving absolute style paths, like 
`<link href="/css/currentStyle.css" rel="stylesheet"/>` - if there is no style at buld time, it's not reson to fail whole build, styles may be added later.

Template's `moduleName` full system paths leaking into production builds

image


Build failing with 
```
   staticHelpers: true,
   staticComponents: true
```
due to resolution erros

**Comment by lifeart** [comment]
If current changes looks well, can we get it merged?

**Comment by ef4** [comment]
Thanks, this looks great.

**Comment by ef4** [comment]
> if there is no style at buld time, it's not reson to fail whole build, styles may be added later. (we can warn about it?)

Yes, we already warn about missing `<script>`, we can make styles be a warning too.

We already support putting a `data-embroider-ignore` attribute on `<script>` if you want embroider to ignore a script tag. We should make sure the same works for `<link rel="stylesheet">`.

**Comment by ef4** [comment]
I think each of these deserves its own followup issue:

 - stylesheet link that's not available should be a warning
 - full system paths in moduleName
 - `can't resolve ..componentsmy-table.js`. This one is probably a windows path problem, it was trying to say `../components/my-table.js`

**Pull request merged**
