### PR TITLE
vite fix custom base url

### LINKED ISSUE #2189: [Vite] @embroider/virtual/vendor.js is not covered properly by Vite asset handling
The `<script src="/@embroider/virtual/vendor.js"></script>` in the _source_ index.html is not properly converted in the _output_ `dist/index.jtml`. As other assets, in a production build it should get fingerprinted and take [base](https://vite.dev/config/shared-options.html#base) into account. Not doing so makes this break production deployments.

## Expected

With a `base` of `https://cdn.example.com/`:

```
<script src="https://cdn.example.com/@embroider/virtual/vendor-Dx01Zf34.js"></script>
```

## Actual

```
<script src="/@embroider/virtual/vendor.js"></script>
```

### PR DESCRIPTION
**Pull request by patricklx**
this is for vite build.
Vite does only prefix base path to known public files. So, they do have to exist. This only happens on build, during dev all urls are prefixed...
Which does not work for virtual vendor.js and others that are generated later in the process 
https://github.com/vitejs/vite/blob/fe30349d350ef08bccd56404ccc3e6d6e0a2e156/packages/vite/src/node/plugins/html.ts#L456

also, any custom middleware needs to handle this, since base path can be setup during dev

fixes #2189

### CODE REVIEW

**Comment by void-mAlex** [comment]
how about making all those URLs relative instead?

**Comment by patricklx** [comment]
> how about making all those URLs relative instead?

that doesn't work, because website can open at some level deeper.
e.g my-website.com/my-app/current-page
and then that doesn't work anymore

**Comment by patricklx** [comment]
Maybe that vendor.js could be removed anyway. And directly import loaderjs in entry point?
Other things can also all be imported directly? It would break backwards compatibility though

**Comment by void-mAlex** [comment]
> my-website.com/my-app/current-page
is exactly why it should be relative
today, the no1 reason why you can't use ./ for root_url is because of the testing framework and how that assumes things to be available
but making everything relative is the way to go

**Comment by patricklx** [comment]
But then it would access ./my-page/current-page/asset/some-asset.js ?
For a src=./asset/some-asset.js

**Comment by void-mAlex** [comment]
> But then it would access ./my-page/current-page/asset/some-asset.js ? For a src=./asset/some-asset.js

why would it?
it'a all about build time relativity and relative to initial html

**Comment by patricklx** [comment]
Vite keeps it like that in the output...

Alex ***@***.***> schrieb am So., 14. Juli 2024, 19:52:

**Comment by patricklx** [comment]
It's not a module... That's why

Patrick Pircher ***@***.***> schrieb am So., 14. Juli 2024,
20:21:

**Comment by void-mAlex** [comment]
> Vite keeps it like that in the output..

yes, have it relative to begin with and you don't have an issue ( if there is somewhere I can see this falling short in today's world is the router) but that has problems regardless so you lose nothing by having always relative urls which should be the default as it enables exactly the kind of deploy you mentioned of `my-website.com/my-app/`

**Comment by ef4** [comment]
vendor.js has to remain a script, not a module. That's why it continues to exist as a separate thing. All the code in it expects to run in script context.

**Comment by patricklx** [comment]
i found that this is already done automatically by vite. https://vitejs.dev/guide/build.html#public-base-path
not sure why it was not working for me

**Comment by void-mAlex** [comment]
I would hate for us to re introduce this root url concept in vite world
between base html tag and using relative paths we have better tools to deal wiht this without adding back what I consider broken concepts

**Comment by patricklx** [comment]
> I would hate for us to re introduce this root url concept in vite world between base html tag and using relative paths we have better tools to deal wiht this without adding back what I consider broken concepts

i had older code still there. have a look now

**Comment by ef4** [comment]
The implementation changes look good. For the test, I'd rather not maintain a whole separate matrix full of tests for this case. Can we perhaps add an additional `basePath` argument to `buildViteInternalsTest()` and invoke it from within the existing matrix of tests?

**Pull request closed without merging**
