### PR TITLE
Make macro configs static

### PR DESCRIPTION
**Pull request by simonihmig**
Same as #1815, this time targeting `main`

### CODE REVIEW

**Review by mansona — COMMENTED** [review]
Shouldn't we just merge stable into main after we release stable and then the changes will come along? 🤔

**Comment by simonihmig** [comment]
yeah, I wasn't sure how we plan that!? I guess it depends how far the two branches diverged, and where the changes on stable happened? Changes in the macro package should be easy to merge, but not sure if we have others that cause crazy merge conflicts, or that we even don't want in `main`? More on you to decide I guess what makes more sense! :)

**Comment by mansona** [comment]
essentially we agreed collectively that we want to do this stuff as "forward merges" from stable to main, I'll give it a go and see how far I get :)

**Comment by mansona** [comment]
Didn't seem like too hard a merge 👍 https://github.com/embroider-build/embroider/pull/1825

**Comment by simonihmig** [comment]
Even better, closing this!

**Pull request closed without merging**
