### PR TITLE
Run importSync transform later, so ember-auto-import can support importSync

### PR DESCRIPTION
**Pull request by simonihmig**
This runs the transform of importSync in the exit hook, to allow ember-auto-import to do its own transformation *before* us. See https://github.com/ef4/ember-auto-import/pull/347

### CODE REVIEW

**Comment by simonihmig** [comment]
Unrelated canary failures here...

**Comment by simonihmig** [comment]
@ef4 can we merge this?

**Comment by rwjblue** [comment]
@simonihmig the canary failures have been fixed, mind rebasing?

**Review by rwjblue — APPROVED** [review]

**Comment by simonihmig** [comment]
> the canary failures have been fixed, mind rebasing?

Done, green now! Thanks for the review!

**Pull request merged**
