### PR TITLE
Upgrade JSDom to resolve punycode deprecation spew 

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by dpigera** [comment]
I'm having this issue as well. Do you have a recommendation to fix this deprecation? 

```
(node:18180) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

```
$ npm ls punycode 
...
├─┬ @embroider/compat@3.6.0
│ └─┬ jsdom@16.7.0
│   ├─┬ tough-cookie@4.1.4
│   │ └── punycode@2.3.1
│   └─┬ whatwg-url@8.7.0
│     └─┬ tr46@2.1.0
│       └── punycode@2.3.1 deduped
└─┬ eslint@8.57.0
  └─┬ ajv@6.12.6
    └─┬ uri-js@4.4.1
      └── punycode@2.3.1 deduped
      ```

**Comment by NullVoxPopuli** [comment]
I read the deprecation and recommendation backwards -- the solution _is_ to use the punycode package.

However, I don't know how to yet find where punycode is required / imported from where a dep does not declare punycode as a dependency. might need to write a tool

**Comment by NullVoxPopuli** [comment]
Just released aforementioned tool: https://github.com/NullVoxPopuli/punycode-detector

**Comment by NullVoxPopuli** [comment]
This is what needs upgraded / PR'd:

```
❯ pnpm dlx punycode-detector
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
There are 12 imports/requires of 'punycode' : The node builtin (which is deprecated) and not the 'punycode/' userland package.
Set(12) {
  'node_modules/.pnpm/markdown-it@12.3.2/node_modules/markdown-it/lib/index.js',
  'node_modules/.pnpm/markdown-it@13.0.2/node_modules/markdown-it/lib/index.js',
  'node_modules/.pnpm/markdown-it@8.4.2/node_modules/markdown-it/lib/index.js',
  'node_modules/.pnpm/markdown-it@8.4.2/node_modules/markdown-it/dist/markdown-it.js',
  'node_modules/.pnpm/normalize-url@2.0.1/node_modules/normalize-url/index.js',
  'node_modules/.pnpm/psl@1.9.0/node_modules/psl/index.js',
  'node_modules/.pnpm/psl@1.9.0/node_modules/psl/dist/psl.js',
  'node_modules/.pnpm/whatwg-url@5.0.0/node_modules/whatwg-url/lib/url-state-machine.js',
  'node_modules/.pnpm/tr46@2.1.0/node_modules/tr46/index.js',
  'node_modules/.pnpm/whatwg-url@8.7.0/node_modules/whatwg-url/dist/url-state-machine.js',
  'node_modules/.pnpm/tr46@3.0.0/node_modules/tr46/index.js',
  'node_modules/.pnpm/tr46@0.0.3/node_modules/tr46/index.js'
}
```

**Comment by NullVoxPopuli** [comment]
I'll open a new issue.

**Pull request closed without merging**
