### PR TITLE
Add support for import with destDir option

### PR DESCRIPTION
**Pull request by balinterdi**

### CODE REVIEW

**Comment by balinterdi** [comment]
@ef4 We put this PR together with @benedikt during a pair-programming session and it "just works".

A test still needs to be added and I wanted to ask you whether what we did in this PR is a correct way to do it. I'm aware of one issue: our new method, [`addOtherAssets`](https://github.com/embroider-build/embroider/pull/278/files#diff-fbcbb8d4c0d3117c2fb9db39fb54bf5dR401) only has side effects, it doesn't modify the inputTree it receives in any way, so the way it's being called now is not ideal.

We tried to call `addOtherAssets` from the `emberEntrypoints` method, before going through `classicEntrypoints` ([here](https://github.com/embroider-build/embroider/blob/4af5ab3b92/packages/compat/src/compat-app.ts#L147))because it seemed more apt there, but when we did that, the assets weren't copied.

Awaiting your guidance of what/how to improve. Thanks!

**Comment by ef4** [comment]
Thanks, this is good. I added the test because I wanted to start a new test module for all these app.import cases anyway.

**Comment by ef4** [comment]
Fixed https://github.com/embroider-build/embroider/issues/267

**Comment by stefanpenner** [comment]
Nice!

**Pull request merged**
