### PR TITLE
resolve failed macro condition in ember-private-api

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Goal to resolve: https://github.com/embroider-build/embroider/issues/1038

Only occurs when the host-app's ember-source is alpha or beta

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
hm, nevermind, this isn't the fix

**Comment by NullVoxPopuli** [comment]
@ef4 I did it! I just needed to use `*` for the version instead of specific versions

**Comment by NullVoxPopuli** [comment]
I don't know how to make a test for this tho.

**Comment by NullVoxPopuli** [comment]
hm, maybe the `*` breaks non-alpha/non-beta  `ember-source` :thinking: 

based on the failing tests, it seems that the `*` version is used _instead of_ the host app's version?

**Comment by ef4** [comment]
There are two bad things that ember-cli does and we follow for compatibility that were causing trouble here.

One is that dummy apps and addons share a package.json, so adding the peerDep to the addon (which is correct) also adds it to the dummy app (which is unnecessary at best but here actually triggers the following bug).

Two is that we have special logic to cause apps to *not* discover addons in peerDeps, because that's what ember-cli does. So the dummy app stopped discovering the ember-source addon.

I had to adjust the logic so that a peerDep that's also a dep will get discovered.

**Pull request merged**
