### PR TITLE
Passthrough HTML attributes

### LINKED ISSUE #456: Should Embroider passthrough script attributes?
Hi,

should Embroider passthrough the HTML attributes like `defer` on scripts from `app/index.html` into `dist/index.html` for `ember build --environment=production`?

```html
<!-- app/index.html -->
<script src="{{rootURL}}assets/vendor.js" defer></script>
<script src="{{rootURL}}assets/embroider-playground.js" defer></script>

<!-- dist/index.html -->
<script src="/assets/vendor.js"></script>
<script src="/assets/chunk.c1fdfc6b793b9d023c96.js"></script>
<script src="/assets/chunk.4aecffffbd029f26d4de.js"></script>
```

Thanks ☺️

---

Just for curiosity why the `assets/embroider-playground.js` is split into two chunks by default?

### PR DESCRIPTION
**Pull request by bobisjan**
- closes #456 
- [ ] add tests?

### CODE REVIEW

**Comment by ef4** [comment]
I never reviewed this because it has been marked Draft. But this is a real issue worth fixing.

I think maybe only this part is needed?

https://github.com/embroider-build/embroider/pull/588/files#diff-f6871a419b7638a206e71923afc7910d1a3252cdfa5c563a5fb7e455063146b0R74-R76

**Comment by bobisjan** [comment]
TBH I don't recall why the rest was added 🙈, but will look during weekend.

**Comment by bobisjan** [comment]
Not sure where attributes get lost, but _something_ is needed (don't mean that the proposed solution is correct).

When I omit copying of attributes in `PreparedEmberHTML`, then `HTMLEntrypoint` receives `index.html` without the attributes, hence copying in `Placeholder` does nothing (both for scripts and styles).

**Comment by lifeart** [comment]
Hi @bobisjan! Have a good new year! Do you have time to push it forward? I think only tests is missing here

**Comment by bobisjan** [comment]
> Hi @bobisjan! Have a good new year! Do you have time to push it forward? I think only tests is missing here

Hi @lifeart 👋, I’ll give a try during this weekend 🤞

**Comment by mansona** [comment]
It looks like this was covered by https://github.com/embroider-build/embroider/pull/1605 🎉 

thanks again for your contribution

**Pull request closed without merging**
